// Generated by sprotodump. DO NOT EDIT!
// source: ../../Lua/Proto/proto_100_scene.lua ../../Lua/Proto/proto_1_account.lua

using System;
using Sproto;
using System.Collections.Generic;

namespace SprotoType { 
	public class account_create_role {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _career; // tag 0
			public Int64 career {
				get { return _career; }
				set { base.has_field.set_field (0, true); _career = value; }
			}
			public bool HasCareer {
				get { return base.has_field.has_field (0); }
			}

			private string _name; // tag 1
			public string name {
				get { return _name; }
				set { base.has_field.set_field (1, true); _name = value; }
			}
			public bool HasName {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.career = base.deserialize.read_integer ();
						break;
					case 1:
						this.name = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.career, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_string (this.name, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _role_id; // tag 1
			public Int64 role_id {
				get { return _role_id; }
				set { base.has_field.set_field (1, true); _role_id = value; }
			}
			public bool HasRole_id {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.role_id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.role_id, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class account_delete_role {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _role_id; // tag 0
			public Int64 role_id {
				get { return _role_id; }
				set { base.has_field.set_field (0, true); _role_id = value; }
			}
			public bool HasRole_id {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.role_id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.role_id, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class account_get_role_list {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<role_figure> _role_list; // tag 0
			public List<role_figure> role_list {
				get { return _role_list; }
				set { base.has_field.set_field (0, true); _role_list = value; }
			}
			public bool HasRole_list {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.role_list = base.deserialize.read_obj_list<role_figure> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.role_list, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class account_get_server_time {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _server_time; // tag 0
			public Int64 server_time {
				get { return _server_time; }
				set { base.has_field.set_field (0, true); _server_time = value; }
			}
			public bool HasServer_time {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.server_time = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.server_time, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class account_select_role_enter_game {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _role_id; // tag 0
			public Int64 role_id {
				get { return _role_id; }
				set { base.has_field.set_field (0, true); _role_id = value; }
			}
			public bool HasRole_id {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.role_id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.role_id, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class info_item : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _key; // tag 0
		public Int64 key {
			get { return _key; }
			set { base.has_field.set_field (0, true); _key = value; }
		}
		public bool HasKey {
			get { return base.has_field.has_field (0); }
		}

		private string _value; // tag 1
		public string value {
			get { return _value; }
			set { base.has_field.set_field (1, true); _value = value; }
		}
		public bool HasValue {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _time; // tag 2
		public Int64 time {
			get { return _time; }
			set { base.has_field.set_field (2, true); _time = value; }
		}
		public bool HasTime {
			get { return base.has_field.has_field (2); }
		}

		public info_item () : base(max_field_count) {}

		public info_item (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.key = base.deserialize.read_integer ();
					break;
				case 1:
					this.value = base.deserialize.read_string ();
					break;
				case 2:
					this.time = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.key, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.value, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.time, 2);
			}

			return base.serialize.close ();
		}
	}


	public class role_figure : SprotoTypeBase {
		private static int max_field_count = 5;
		
		
		private Int64 _role_id; // tag 0
		public Int64 role_id {
			get { return _role_id; }
			set { base.has_field.set_field (0, true); _role_id = value; }
		}
		public bool HasRole_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _career; // tag 1
		public Int64 career {
			get { return _career; }
			set { base.has_field.set_field (1, true); _career = value; }
		}
		public bool HasCareer {
			get { return base.has_field.has_field (1); }
		}

		private string _name; // tag 2
		public string name {
			get { return _name; }
			set { base.has_field.set_field (2, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _body; // tag 3
		public Int64 body {
			get { return _body; }
			set { base.has_field.set_field (3, true); _body = value; }
		}
		public bool HasBody {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _hair; // tag 4
		public Int64 hair {
			get { return _hair; }
			set { base.has_field.set_field (4, true); _hair = value; }
		}
		public bool HasHair {
			get { return base.has_field.has_field (4); }
		}

		public role_figure () : base(max_field_count) {}

		public role_figure (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.role_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.career = base.deserialize.read_integer ();
					break;
				case 2:
					this.name = base.deserialize.read_string ();
					break;
				case 3:
					this.body = base.deserialize.read_integer ();
					break;
				case 4:
					this.hair = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.role_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.career, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_string (this.name, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.body, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.hair, 4);
			}

			return base.serialize.close ();
		}
	}


	public class scene_cast_skill {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 8;
			
			
			private Int64 _skill_id; // tag 0
			public Int64 skill_id {
				get { return _skill_id; }
				set { base.has_field.set_field (0, true); _skill_id = value; }
			}
			public bool HasSkill_id {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _cur_pos_x; // tag 1
			public Int64 cur_pos_x {
				get { return _cur_pos_x; }
				set { base.has_field.set_field (1, true); _cur_pos_x = value; }
			}
			public bool HasCur_pos_x {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _cur_pos_y; // tag 2
			public Int64 cur_pos_y {
				get { return _cur_pos_y; }
				set { base.has_field.set_field (2, true); _cur_pos_y = value; }
			}
			public bool HasCur_pos_y {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _cur_pos_z; // tag 3
			public Int64 cur_pos_z {
				get { return _cur_pos_z; }
				set { base.has_field.set_field (3, true); _cur_pos_z = value; }
			}
			public bool HasCur_pos_z {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _target_pos_x; // tag 4
			public Int64 target_pos_x {
				get { return _target_pos_x; }
				set { base.has_field.set_field (4, true); _target_pos_x = value; }
			}
			public bool HasTarget_pos_x {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _target_pos_y; // tag 5
			public Int64 target_pos_y {
				get { return _target_pos_y; }
				set { base.has_field.set_field (5, true); _target_pos_y = value; }
			}
			public bool HasTarget_pos_y {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _target_pos_z; // tag 6
			public Int64 target_pos_z {
				get { return _target_pos_z; }
				set { base.has_field.set_field (6, true); _target_pos_z = value; }
			}
			public bool HasTarget_pos_z {
				get { return base.has_field.has_field (6); }
			}

			private Int64 _direction; // tag 7
			public Int64 direction {
				get { return _direction; }
				set { base.has_field.set_field (7, true); _direction = value; }
			}
			public bool HasDirection {
				get { return base.has_field.has_field (7); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.skill_id = base.deserialize.read_integer ();
						break;
					case 1:
						this.cur_pos_x = base.deserialize.read_integer ();
						break;
					case 2:
						this.cur_pos_y = base.deserialize.read_integer ();
						break;
					case 3:
						this.cur_pos_z = base.deserialize.read_integer ();
						break;
					case 4:
						this.target_pos_x = base.deserialize.read_integer ();
						break;
					case 5:
						this.target_pos_y = base.deserialize.read_integer ();
						break;
					case 6:
						this.target_pos_z = base.deserialize.read_integer ();
						break;
					case 7:
						this.direction = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.skill_id, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.cur_pos_x, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.cur_pos_y, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.cur_pos_z, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.target_pos_x, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.target_pos_y, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.target_pos_z, 6);
				}

				if (base.has_field.has_field (7)) {
					base.serialize.write_integer (this.direction, 7);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _skill_id; // tag 1
			public Int64 skill_id {
				get { return _skill_id; }
				set { base.has_field.set_field (1, true); _skill_id = value; }
			}
			public bool HasSkill_id {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _cd_end_time; // tag 2
			public Int64 cd_end_time {
				get { return _cd_end_time; }
				set { base.has_field.set_field (2, true); _cd_end_time = value; }
			}
			public bool HasCd_end_time {
				get { return base.has_field.has_field (2); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.skill_id = base.deserialize.read_integer ();
						break;
					case 2:
						this.cd_end_time = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.skill_id, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.cd_end_time, 2);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_change_aoi_radius {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _radius; // tag 0
			public Int64 radius {
				get { return _radius; }
				set { base.has_field.set_field (0, true); _radius = value; }
			}
			public bool HasRadius {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.radius = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.radius, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_enter_to {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _scene_id; // tag 0
			public Int64 scene_id {
				get { return _scene_id; }
				set { base.has_field.set_field (0, true); _scene_id = value; }
			}
			public bool HasScene_id {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _door_id; // tag 1
			public Int64 door_id {
				get { return _door_id; }
				set { base.has_field.set_field (1, true); _door_id = value; }
			}
			public bool HasDoor_id {
				get { return base.has_field.has_field (1); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.scene_id = base.deserialize.read_integer ();
						break;
					case 1:
						this.door_id = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.scene_id, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.door_id, 1);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_get_main_role_info {
	
		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private scene_main_role_info _role_info; // tag 0
			public scene_main_role_info role_info {
				get { return _role_info; }
				set { base.has_field.set_field (0, true); _role_info = value; }
			}
			public bool HasRole_info {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.role_info = base.deserialize.read_obj<scene_main_role_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.role_info, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_get_objs_info_change {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<scene_obj_info> _obj_infos; // tag 0
			public List<scene_obj_info> obj_infos {
				get { return _obj_infos; }
				set { base.has_field.set_field (0, true); _obj_infos = value; }
			}
			public bool HasObj_infos {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.obj_infos = base.deserialize.read_obj_list<scene_obj_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.obj_infos, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_get_role_look_info {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private Int64 _uid; // tag 0
			public Int64 uid {
				get { return _uid; }
				set { base.has_field.set_field (0, true); _uid = value; }
			}
			public bool HasUid {
				get { return base.has_field.has_field (0); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.uid = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.uid, 0);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 2;
			
			
			private Int64 _result; // tag 0
			public Int64 result {
				get { return _result; }
				set { base.has_field.set_field (0, true); _result = value; }
			}
			public bool HasResult {
				get { return base.has_field.has_field (0); }
			}

			private scene_role_looks_info _role_looks_info; // tag 1
			public scene_role_looks_info role_looks_info {
				get { return _role_looks_info; }
				set { base.has_field.set_field (1, true); _role_looks_info = value; }
			}
			public bool HasRole_looks_info {
				get { return base.has_field.has_field (1); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.result = base.deserialize.read_integer ();
						break;
					case 1:
						this.role_looks_info = base.deserialize.read_obj<scene_role_looks_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.result, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_obj (this.role_looks_info, 1);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_hurt_defender_info : SprotoTypeBase {
		private static int max_field_count = 4;
		
		
		private Int64 _uid; // tag 0
		public Int64 uid {
			get { return _uid; }
			set { base.has_field.set_field (0, true); _uid = value; }
		}
		public bool HasUid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _change_num; // tag 1
		public Int64 change_num {
			get { return _change_num; }
			set { base.has_field.set_field (1, true); _change_num = value; }
		}
		public bool HasChange_num {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _cur_hp; // tag 2
		public Int64 cur_hp {
			get { return _cur_hp; }
			set { base.has_field.set_field (2, true); _cur_hp = value; }
		}
		public bool HasCur_hp {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _flag; // tag 3
		public Int64 flag {
			get { return _flag; }
			set { base.has_field.set_field (3, true); _flag = value; }
		}
		public bool HasFlag {
			get { return base.has_field.has_field (3); }
		}

		public scene_hurt_defender_info () : base(max_field_count) {}

		public scene_hurt_defender_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.uid = base.deserialize.read_integer ();
					break;
				case 1:
					this.change_num = base.deserialize.read_integer ();
					break;
				case 2:
					this.cur_hp = base.deserialize.read_integer ();
					break;
				case 3:
					this.flag = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.uid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.change_num, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.cur_hp, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.flag, 3);
			}

			return base.serialize.close ();
		}
	}


	public class scene_hurt_event_info : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _attacker_uid; // tag 0
		public Int64 attacker_uid {
			get { return _attacker_uid; }
			set { base.has_field.set_field (0, true); _attacker_uid = value; }
		}
		public bool HasAttacker_uid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _time; // tag 1
		public Int64 time {
			get { return _time; }
			set { base.has_field.set_field (1, true); _time = value; }
		}
		public bool HasTime {
			get { return base.has_field.has_field (1); }
		}

		private List<scene_hurt_defender_info> _defenders; // tag 2
		public List<scene_hurt_defender_info> defenders {
			get { return _defenders; }
			set { base.has_field.set_field (2, true); _defenders = value; }
		}
		public bool HasDefenders {
			get { return base.has_field.has_field (2); }
		}

		public scene_hurt_event_info () : base(max_field_count) {}

		public scene_hurt_event_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.attacker_uid = base.deserialize.read_integer ();
					break;
				case 1:
					this.time = base.deserialize.read_integer ();
					break;
				case 2:
					this.defenders = base.deserialize.read_obj_list<scene_hurt_defender_info> ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.attacker_uid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.time, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_obj (this.defenders, 2);
			}

			return base.serialize.close ();
		}
	}


	public class scene_listen_hurt_event {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<scene_hurt_event_info> _events; // tag 0
			public List<scene_hurt_event_info> events {
				get { return _events; }
				set { base.has_field.set_field (0, true); _events = value; }
			}
			public bool HasEvents {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.events = base.deserialize.read_obj_list<scene_hurt_event_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.events, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_listen_skill_event {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private List<scene_skill_event_info> _events; // tag 0
			public List<scene_skill_event_info> events {
				get { return _events; }
				set { base.has_field.set_field (0, true); _events = value; }
			}
			public bool HasEvents {
				get { return base.has_field.has_field (0); }
			}

			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.events = base.deserialize.read_obj_list<scene_skill_event_info> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_obj (this.events, 0);
				}

				return base.serialize.close ();
			}
		}


	}


	public class scene_main_role_info : SprotoTypeBase {
		private static int max_field_count = 13;
		
		
		private Int64 _scene_uid; // tag 0
		public Int64 scene_uid {
			get { return _scene_uid; }
			set { base.has_field.set_field (0, true); _scene_uid = value; }
		}
		public bool HasScene_uid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _role_id; // tag 1
		public Int64 role_id {
			get { return _role_id; }
			set { base.has_field.set_field (1, true); _role_id = value; }
		}
		public bool HasRole_id {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _career; // tag 2
		public Int64 career {
			get { return _career; }
			set { base.has_field.set_field (2, true); _career = value; }
		}
		public bool HasCareer {
			get { return base.has_field.has_field (2); }
		}

		private string _name; // tag 3
		public string name {
			get { return _name; }
			set { base.has_field.set_field (3, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _scene_id; // tag 4
		public Int64 scene_id {
			get { return _scene_id; }
			set { base.has_field.set_field (4, true); _scene_id = value; }
		}
		public bool HasScene_id {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _pos_x; // tag 5
		public Int64 pos_x {
			get { return _pos_x; }
			set { base.has_field.set_field (5, true); _pos_x = value; }
		}
		public bool HasPos_x {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _pos_y; // tag 6
		public Int64 pos_y {
			get { return _pos_y; }
			set { base.has_field.set_field (6, true); _pos_y = value; }
		}
		public bool HasPos_y {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _pos_z; // tag 7
		public Int64 pos_z {
			get { return _pos_z; }
			set { base.has_field.set_field (7, true); _pos_z = value; }
		}
		public bool HasPos_z {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _cur_hp; // tag 8
		public Int64 cur_hp {
			get { return _cur_hp; }
			set { base.has_field.set_field (8, true); _cur_hp = value; }
		}
		public bool HasCur_hp {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _max_hp; // tag 9
		public Int64 max_hp {
			get { return _max_hp; }
			set { base.has_field.set_field (9, true); _max_hp = value; }
		}
		public bool HasMax_hp {
			get { return base.has_field.has_field (9); }
		}

		private scene_role_base_info _base_info; // tag 10
		public scene_role_base_info base_info {
			get { return _base_info; }
			set { base.has_field.set_field (10, true); _base_info = value; }
		}
		public bool HasBase_info {
			get { return base.has_field.has_field (10); }
		}

		private Int64 _coin; // tag 11
		public Int64 coin {
			get { return _coin; }
			set { base.has_field.set_field (11, true); _coin = value; }
		}
		public bool HasCoin {
			get { return base.has_field.has_field (11); }
		}

		private Int64 _diamond; // tag 12
		public Int64 diamond {
			get { return _diamond; }
			set { base.has_field.set_field (12, true); _diamond = value; }
		}
		public bool HasDiamond {
			get { return base.has_field.has_field (12); }
		}

		public scene_main_role_info () : base(max_field_count) {}

		public scene_main_role_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.scene_uid = base.deserialize.read_integer ();
					break;
				case 1:
					this.role_id = base.deserialize.read_integer ();
					break;
				case 2:
					this.career = base.deserialize.read_integer ();
					break;
				case 3:
					this.name = base.deserialize.read_string ();
					break;
				case 4:
					this.scene_id = base.deserialize.read_integer ();
					break;
				case 5:
					this.pos_x = base.deserialize.read_integer ();
					break;
				case 6:
					this.pos_y = base.deserialize.read_integer ();
					break;
				case 7:
					this.pos_z = base.deserialize.read_integer ();
					break;
				case 8:
					this.cur_hp = base.deserialize.read_integer ();
					break;
				case 9:
					this.max_hp = base.deserialize.read_integer ();
					break;
				case 10:
					this.base_info = base.deserialize.read_obj<scene_role_base_info> ();
					break;
				case 11:
					this.coin = base.deserialize.read_integer ();
					break;
				case 12:
					this.diamond = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.scene_uid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.role_id, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.career, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_string (this.name, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.scene_id, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.pos_x, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.pos_y, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.pos_z, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.cur_hp, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.max_hp, 9);
			}

			if (base.has_field.has_field (10)) {
				base.serialize.write_obj (this.base_info, 10);
			}

			if (base.has_field.has_field (11)) {
				base.serialize.write_integer (this.coin, 11);
			}

			if (base.has_field.has_field (12)) {
				base.serialize.write_integer (this.diamond, 12);
			}

			return base.serialize.close ();
		}
	}


	public class scene_monster_info : SprotoTypeBase {
		private static int max_field_count = 4;
		
		
		private Int64 _monster_id; // tag 0
		public Int64 monster_id {
			get { return _monster_id; }
			set { base.has_field.set_field (0, true); _monster_id = value; }
		}
		public bool HasMonster_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _monster_type_id; // tag 1
		public Int64 monster_type_id {
			get { return _monster_type_id; }
			set { base.has_field.set_field (1, true); _monster_type_id = value; }
		}
		public bool HasMonster_type_id {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _hp; // tag 2
		public Int64 hp {
			get { return _hp; }
			set { base.has_field.set_field (2, true); _hp = value; }
		}
		public bool HasHp {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _maxhp; // tag 3
		public Int64 maxhp {
			get { return _maxhp; }
			set { base.has_field.set_field (3, true); _maxhp = value; }
		}
		public bool HasMaxhp {
			get { return base.has_field.has_field (3); }
		}

		public scene_monster_info () : base(max_field_count) {}

		public scene_monster_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.monster_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.monster_type_id = base.deserialize.read_integer ();
					break;
				case 2:
					this.hp = base.deserialize.read_integer ();
					break;
				case 3:
					this.maxhp = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.monster_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.monster_type_id, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.hp, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.maxhp, 3);
			}

			return base.serialize.close ();
		}
	}


	public class scene_npc_info : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _npc_id; // tag 0
		public Int64 npc_id {
			get { return _npc_id; }
			set { base.has_field.set_field (0, true); _npc_id = value; }
		}
		public bool HasNpc_id {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _npc_type_id; // tag 1
		public Int64 npc_type_id {
			get { return _npc_type_id; }
			set { base.has_field.set_field (1, true); _npc_type_id = value; }
		}
		public bool HasNpc_type_id {
			get { return base.has_field.has_field (1); }
		}

		public scene_npc_info () : base(max_field_count) {}

		public scene_npc_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.npc_id = base.deserialize.read_integer ();
					break;
				case 1:
					this.npc_type_id = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.npc_id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.npc_type_id, 1);
			}

			return base.serialize.close ();
		}
	}


	public class scene_obj_info : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _scene_obj_uid; // tag 0
		public Int64 scene_obj_uid {
			get { return _scene_obj_uid; }
			set { base.has_field.set_field (0, true); _scene_obj_uid = value; }
		}
		public bool HasScene_obj_uid {
			get { return base.has_field.has_field (0); }
		}

		private List<info_item> _info_list; // tag 1
		public List<info_item> info_list {
			get { return _info_list; }
			set { base.has_field.set_field (1, true); _info_list = value; }
		}
		public bool HasInfo_list {
			get { return base.has_field.has_field (1); }
		}

		public scene_obj_info () : base(max_field_count) {}

		public scene_obj_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.scene_obj_uid = base.deserialize.read_integer ();
					break;
				case 1:
					this.info_list = base.deserialize.read_obj_list<info_item> ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.scene_obj_uid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_obj (this.info_list, 1);
			}

			return base.serialize.close ();
		}
	}


	public class scene_role_base_info : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _level; // tag 0
		public Int64 level {
			get { return _level; }
			set { base.has_field.set_field (0, true); _level = value; }
		}
		public bool HasLevel {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _career; // tag 1
		public Int64 career {
			get { return _career; }
			set { base.has_field.set_field (1, true); _career = value; }
		}
		public bool HasCareer {
			get { return base.has_field.has_field (1); }
		}

		public scene_role_base_info () : base(max_field_count) {}

		public scene_role_base_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.level = base.deserialize.read_integer ();
					break;
				case 1:
					this.career = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.level, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.career, 1);
			}

			return base.serialize.close ();
		}
	}


	public class scene_role_looks_info : SprotoTypeBase {
		private static int max_field_count = 9;
		
		
		private Int64 _career; // tag 0
		public Int64 career {
			get { return _career; }
			set { base.has_field.set_field (0, true); _career = value; }
		}
		public bool HasCareer {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _body; // tag 1
		public Int64 body {
			get { return _body; }
			set { base.has_field.set_field (1, true); _body = value; }
		}
		public bool HasBody {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _hair; // tag 2
		public Int64 hair {
			get { return _hair; }
			set { base.has_field.set_field (2, true); _hair = value; }
		}
		public bool HasHair {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _weapon; // tag 3
		public Int64 weapon {
			get { return _weapon; }
			set { base.has_field.set_field (3, true); _weapon = value; }
		}
		public bool HasWeapon {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _wing; // tag 4
		public Int64 wing {
			get { return _wing; }
			set { base.has_field.set_field (4, true); _wing = value; }
		}
		public bool HasWing {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _horse; // tag 5
		public Int64 horse {
			get { return _horse; }
			set { base.has_field.set_field (5, true); _horse = value; }
		}
		public bool HasHorse {
			get { return base.has_field.has_field (5); }
		}

		private string _name; // tag 6
		public string name {
			get { return _name; }
			set { base.has_field.set_field (6, true); _name = value; }
		}
		public bool HasName {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _hp; // tag 7
		public Int64 hp {
			get { return _hp; }
			set { base.has_field.set_field (7, true); _hp = value; }
		}
		public bool HasHp {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _max_hp; // tag 8
		public Int64 max_hp {
			get { return _max_hp; }
			set { base.has_field.set_field (8, true); _max_hp = value; }
		}
		public bool HasMax_hp {
			get { return base.has_field.has_field (8); }
		}

		public scene_role_looks_info () : base(max_field_count) {}

		public scene_role_looks_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.career = base.deserialize.read_integer ();
					break;
				case 1:
					this.body = base.deserialize.read_integer ();
					break;
				case 2:
					this.hair = base.deserialize.read_integer ();
					break;
				case 3:
					this.weapon = base.deserialize.read_integer ();
					break;
				case 4:
					this.wing = base.deserialize.read_integer ();
					break;
				case 5:
					this.horse = base.deserialize.read_integer ();
					break;
				case 6:
					this.name = base.deserialize.read_string ();
					break;
				case 7:
					this.hp = base.deserialize.read_integer ();
					break;
				case 8:
					this.max_hp = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.career, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.body, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.hair, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.weapon, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.wing, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.horse, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_string (this.name, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.hp, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.max_hp, 8);
			}

			return base.serialize.close ();
		}
	}


	public class scene_skill_event_info : SprotoTypeBase {
		private static int max_field_count = 12;
		
		
		private Int64 _attacker_uid; // tag 0
		public Int64 attacker_uid {
			get { return _attacker_uid; }
			set { base.has_field.set_field (0, true); _attacker_uid = value; }
		}
		public bool HasAttacker_uid {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _skill_id; // tag 1
		public Int64 skill_id {
			get { return _skill_id; }
			set { base.has_field.set_field (1, true); _skill_id = value; }
		}
		public bool HasSkill_id {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _skill_lv; // tag 2
		public Int64 skill_lv {
			get { return _skill_lv; }
			set { base.has_field.set_field (2, true); _skill_lv = value; }
		}
		public bool HasSkill_lv {
			get { return base.has_field.has_field (2); }
		}

		private Int64 _attacker_pos_x; // tag 3
		public Int64 attacker_pos_x {
			get { return _attacker_pos_x; }
			set { base.has_field.set_field (3, true); _attacker_pos_x = value; }
		}
		public bool HasAttacker_pos_x {
			get { return base.has_field.has_field (3); }
		}

		private Int64 _attacker_pos_y; // tag 4
		public Int64 attacker_pos_y {
			get { return _attacker_pos_y; }
			set { base.has_field.set_field (4, true); _attacker_pos_y = value; }
		}
		public bool HasAttacker_pos_y {
			get { return base.has_field.has_field (4); }
		}

		private Int64 _attacker_pos_z; // tag 5
		public Int64 attacker_pos_z {
			get { return _attacker_pos_z; }
			set { base.has_field.set_field (5, true); _attacker_pos_z = value; }
		}
		public bool HasAttacker_pos_z {
			get { return base.has_field.has_field (5); }
		}

		private Int64 _target_pos_x; // tag 6
		public Int64 target_pos_x {
			get { return _target_pos_x; }
			set { base.has_field.set_field (6, true); _target_pos_x = value; }
		}
		public bool HasTarget_pos_x {
			get { return base.has_field.has_field (6); }
		}

		private Int64 _target_pos_y; // tag 7
		public Int64 target_pos_y {
			get { return _target_pos_y; }
			set { base.has_field.set_field (7, true); _target_pos_y = value; }
		}
		public bool HasTarget_pos_y {
			get { return base.has_field.has_field (7); }
		}

		private Int64 _target_pos_z; // tag 8
		public Int64 target_pos_z {
			get { return _target_pos_z; }
			set { base.has_field.set_field (8, true); _target_pos_z = value; }
		}
		public bool HasTarget_pos_z {
			get { return base.has_field.has_field (8); }
		}

		private Int64 _direction; // tag 9
		public Int64 direction {
			get { return _direction; }
			set { base.has_field.set_field (9, true); _direction = value; }
		}
		public bool HasDirection {
			get { return base.has_field.has_field (9); }
		}

		private Int64 _time; // tag 10
		public Int64 time {
			get { return _time; }
			set { base.has_field.set_field (10, true); _time = value; }
		}
		public bool HasTime {
			get { return base.has_field.has_field (10); }
		}

		private Int64 _flag; // tag 11
		public Int64 flag {
			get { return _flag; }
			set { base.has_field.set_field (11, true); _flag = value; }
		}
		public bool HasFlag {
			get { return base.has_field.has_field (11); }
		}

		public scene_skill_event_info () : base(max_field_count) {}

		public scene_skill_event_info (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.attacker_uid = base.deserialize.read_integer ();
					break;
				case 1:
					this.skill_id = base.deserialize.read_integer ();
					break;
				case 2:
					this.skill_lv = base.deserialize.read_integer ();
					break;
				case 3:
					this.attacker_pos_x = base.deserialize.read_integer ();
					break;
				case 4:
					this.attacker_pos_y = base.deserialize.read_integer ();
					break;
				case 5:
					this.attacker_pos_z = base.deserialize.read_integer ();
					break;
				case 6:
					this.target_pos_x = base.deserialize.read_integer ();
					break;
				case 7:
					this.target_pos_y = base.deserialize.read_integer ();
					break;
				case 8:
					this.target_pos_z = base.deserialize.read_integer ();
					break;
				case 9:
					this.direction = base.deserialize.read_integer ();
					break;
				case 10:
					this.time = base.deserialize.read_integer ();
					break;
				case 11:
					this.flag = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.attacker_uid, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.skill_id, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.skill_lv, 2);
			}

			if (base.has_field.has_field (3)) {
				base.serialize.write_integer (this.attacker_pos_x, 3);
			}

			if (base.has_field.has_field (4)) {
				base.serialize.write_integer (this.attacker_pos_y, 4);
			}

			if (base.has_field.has_field (5)) {
				base.serialize.write_integer (this.attacker_pos_z, 5);
			}

			if (base.has_field.has_field (6)) {
				base.serialize.write_integer (this.target_pos_x, 6);
			}

			if (base.has_field.has_field (7)) {
				base.serialize.write_integer (this.target_pos_y, 7);
			}

			if (base.has_field.has_field (8)) {
				base.serialize.write_integer (this.target_pos_z, 8);
			}

			if (base.has_field.has_field (9)) {
				base.serialize.write_integer (this.direction, 9);
			}

			if (base.has_field.has_field (10)) {
				base.serialize.write_integer (this.time, 10);
			}

			if (base.has_field.has_field (11)) {
				base.serialize.write_integer (this.flag, 11);
			}

			return base.serialize.close ();
		}
	}


	public class scene_walk {
	
		public class request : SprotoTypeBase {
			private static int max_field_count = 7;
			
			
			private Int64 _start_x; // tag 0
			public Int64 start_x {
				get { return _start_x; }
				set { base.has_field.set_field (0, true); _start_x = value; }
			}
			public bool HasStart_x {
				get { return base.has_field.has_field (0); }
			}

			private Int64 _start_y; // tag 1
			public Int64 start_y {
				get { return _start_y; }
				set { base.has_field.set_field (1, true); _start_y = value; }
			}
			public bool HasStart_y {
				get { return base.has_field.has_field (1); }
			}

			private Int64 _start_z; // tag 2
			public Int64 start_z {
				get { return _start_z; }
				set { base.has_field.set_field (2, true); _start_z = value; }
			}
			public bool HasStart_z {
				get { return base.has_field.has_field (2); }
			}

			private Int64 _end_x; // tag 3
			public Int64 end_x {
				get { return _end_x; }
				set { base.has_field.set_field (3, true); _end_x = value; }
			}
			public bool HasEnd_x {
				get { return base.has_field.has_field (3); }
			}

			private Int64 _end_z; // tag 4
			public Int64 end_z {
				get { return _end_z; }
				set { base.has_field.set_field (4, true); _end_z = value; }
			}
			public bool HasEnd_z {
				get { return base.has_field.has_field (4); }
			}

			private Int64 _time; // tag 5
			public Int64 time {
				get { return _time; }
				set { base.has_field.set_field (5, true); _time = value; }
			}
			public bool HasTime {
				get { return base.has_field.has_field (5); }
			}

			private Int64 _jump_state; // tag 6
			public Int64 jump_state {
				get { return _jump_state; }
				set { base.has_field.set_field (6, true); _jump_state = value; }
			}
			public bool HasJump_state {
				get { return base.has_field.has_field (6); }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.start_x = base.deserialize.read_integer ();
						break;
					case 1:
						this.start_y = base.deserialize.read_integer ();
						break;
					case 2:
						this.start_z = base.deserialize.read_integer ();
						break;
					case 3:
						this.end_x = base.deserialize.read_integer ();
						break;
					case 4:
						this.end_z = base.deserialize.read_integer ();
						break;
					case 5:
						this.time = base.deserialize.read_integer ();
						break;
					case 6:
						this.jump_state = base.deserialize.read_integer ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.start_x, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.start_y, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_integer (this.start_z, 2);
				}

				if (base.has_field.has_field (3)) {
					base.serialize.write_integer (this.end_x, 3);
				}

				if (base.has_field.has_field (4)) {
					base.serialize.write_integer (this.end_z, 4);
				}

				if (base.has_field.has_field (5)) {
					base.serialize.write_integer (this.time, 5);
				}

				if (base.has_field.has_field (6)) {
					base.serialize.write_integer (this.jump_state, 6);
				}

				return base.serialize.close ();
			}
		}


		public class response : SprotoTypeBase {
			private static int max_field_count = 0;
			
			
			public response () : base(max_field_count) {}

			public response (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				return base.serialize.close ();
			}
		}


	}


}


public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<account_create_role> (account_create_role.Tag);
		Protocol.SetRequest<SprotoType.account_create_role.request> (account_create_role.Tag);
		Protocol.SetResponse<SprotoType.account_create_role.response> (account_create_role.Tag);

		Protocol.SetProtocol<account_delete_role> (account_delete_role.Tag);
		Protocol.SetRequest<SprotoType.account_delete_role.request> (account_delete_role.Tag);
		Protocol.SetResponse<SprotoType.account_delete_role.response> (account_delete_role.Tag);

		Protocol.SetProtocol<account_get_role_list> (account_get_role_list.Tag);
		Protocol.SetResponse<SprotoType.account_get_role_list.response> (account_get_role_list.Tag);

		Protocol.SetProtocol<account_get_server_time> (account_get_server_time.Tag);
		Protocol.SetResponse<SprotoType.account_get_server_time.response> (account_get_server_time.Tag);

		Protocol.SetProtocol<account_select_role_enter_game> (account_select_role_enter_game.Tag);
		Protocol.SetRequest<SprotoType.account_select_role_enter_game.request> (account_select_role_enter_game.Tag);
		Protocol.SetResponse<SprotoType.account_select_role_enter_game.response> (account_select_role_enter_game.Tag);

		Protocol.SetProtocol<scene_cast_skill> (scene_cast_skill.Tag);
		Protocol.SetRequest<SprotoType.scene_cast_skill.request> (scene_cast_skill.Tag);
		Protocol.SetResponse<SprotoType.scene_cast_skill.response> (scene_cast_skill.Tag);

		Protocol.SetProtocol<scene_change_aoi_radius> (scene_change_aoi_radius.Tag);
		Protocol.SetRequest<SprotoType.scene_change_aoi_radius.request> (scene_change_aoi_radius.Tag);

		Protocol.SetProtocol<scene_enter_to> (scene_enter_to.Tag);
		Protocol.SetRequest<SprotoType.scene_enter_to.request> (scene_enter_to.Tag);
		Protocol.SetResponse<SprotoType.scene_enter_to.response> (scene_enter_to.Tag);

		Protocol.SetProtocol<scene_get_main_role_info> (scene_get_main_role_info.Tag);
		Protocol.SetResponse<SprotoType.scene_get_main_role_info.response> (scene_get_main_role_info.Tag);

		Protocol.SetProtocol<scene_get_objs_info_change> (scene_get_objs_info_change.Tag);
		Protocol.SetRequest<SprotoType.scene_get_objs_info_change.request> (scene_get_objs_info_change.Tag);
		Protocol.SetResponse<SprotoType.scene_get_objs_info_change.response> (scene_get_objs_info_change.Tag);

		Protocol.SetProtocol<scene_get_role_look_info> (scene_get_role_look_info.Tag);
		Protocol.SetRequest<SprotoType.scene_get_role_look_info.request> (scene_get_role_look_info.Tag);
		Protocol.SetResponse<SprotoType.scene_get_role_look_info.response> (scene_get_role_look_info.Tag);

		Protocol.SetProtocol<scene_listen_hurt_event> (scene_listen_hurt_event.Tag);
		Protocol.SetRequest<SprotoType.scene_listen_hurt_event.request> (scene_listen_hurt_event.Tag);
		Protocol.SetResponse<SprotoType.scene_listen_hurt_event.response> (scene_listen_hurt_event.Tag);

		Protocol.SetProtocol<scene_listen_skill_event> (scene_listen_skill_event.Tag);
		Protocol.SetRequest<SprotoType.scene_listen_skill_event.request> (scene_listen_skill_event.Tag);
		Protocol.SetResponse<SprotoType.scene_listen_skill_event.response> (scene_listen_skill_event.Tag);

		Protocol.SetProtocol<scene_walk> (scene_walk.Tag);
		Protocol.SetRequest<SprotoType.scene_walk.request> (scene_walk.Tag);
		Protocol.SetResponse<SprotoType.scene_walk.response> (scene_walk.Tag);

	}

	public class account_create_role {
		public const int Tag = 3;
	}

	public class account_delete_role {
		public const int Tag = 4;
	}

	public class account_get_role_list {
		public const int Tag = 2;
	}

	public class account_get_server_time {
		public const int Tag = 1;
	}

	public class account_select_role_enter_game {
		public const int Tag = 5;
	}

	public class scene_cast_skill {
		public const int Tag = 105;
	}

	public class scene_change_aoi_radius {
		public const int Tag = 103;
	}

	public class scene_enter_to {
		public const int Tag = 108;
	}

	public class scene_get_main_role_info {
		public const int Tag = 100;
	}

	public class scene_get_objs_info_change {
		public const int Tag = 102;
	}

	public class scene_get_role_look_info {
		public const int Tag = 104;
	}

	public class scene_listen_hurt_event {
		public const int Tag = 107;
	}

	public class scene_listen_skill_event {
		public const int Tag = 106;
	}

	public class scene_walk {
		public const int Tag = 101;
	}

}