local util = require "util"
local serpent = require "serpent"

local fmt_file_header = [[
-- Code generated by sprotodump
-- DO NOT EDIT!
return ]]

local stream = {}
stream.__index = stream

function stream:write(str)
    table.insert(self.lines, str)
end

function stream:dump()
    return table.concat(self.lines, "\n")
end

local function new_stream()
    local obj = {
        lines = {}
    }
    return setmetatable(obj, stream)
end

local function main(trunk, build, param)
    local outfile = param.outfile or "sproto_list.lua"
    local s = serpent.block(build, {comment=false})
    local out = table.concat({fmt_file_header, s}, '')
    util.write_file(outfile, out, "w")
end

return main
