//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_RuntimePlatformWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.RuntimePlatform));
		L.RegVar("OSXEditor", get_OSXEditor, null);
		L.RegVar("OSXPlayer", get_OSXPlayer, null);
		L.RegVar("WindowsPlayer", get_WindowsPlayer, null);
		L.RegVar("WindowsEditor", get_WindowsEditor, null);
		L.RegVar("IPhonePlayer", get_IPhonePlayer, null);
		L.RegVar("Android", get_Android, null);
		L.RegVar("LinuxPlayer", get_LinuxPlayer, null);
		L.RegVar("LinuxEditor", get_LinuxEditor, null);
		L.RegVar("WebGLPlayer", get_WebGLPlayer, null);
		L.RegVar("WSAPlayerX86", get_WSAPlayerX86, null);
		L.RegVar("WSAPlayerX64", get_WSAPlayerX64, null);
		L.RegVar("WSAPlayerARM", get_WSAPlayerARM, null);
		L.RegVar("TizenPlayer", get_TizenPlayer, null);
		L.RegVar("PSP2", get_PSP2, null);
		L.RegVar("PS4", get_PS4, null);
		L.RegVar("XboxOne", get_XboxOne, null);
		L.RegVar("tvOS", get_tvOS, null);
		L.RegVar("Switch", get_Switch, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.RuntimePlatform>.Check = CheckType;
		StackTraits<UnityEngine.RuntimePlatform>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.RuntimePlatform arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.RuntimePlatform), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OSXEditor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.OSXEditor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OSXPlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.OSXPlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WindowsPlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WindowsPlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WindowsEditor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WindowsEditor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IPhonePlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.IPhonePlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Android(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.Android);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LinuxPlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.LinuxPlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LinuxEditor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.LinuxEditor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WebGLPlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WebGLPlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WSAPlayerX86(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WSAPlayerX86);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WSAPlayerX64(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WSAPlayerX64);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WSAPlayerARM(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.WSAPlayerARM);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TizenPlayer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.TizenPlayer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PSP2(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.PSP2);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PS4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.PS4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_XboxOne(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.XboxOne);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tvOS(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.tvOS);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Switch(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RuntimePlatform.Switch);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.RuntimePlatform o = (UnityEngine.RuntimePlatform)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

